#!/usr/bin/env python
from misc.utility.scons_hints import *

import build_scripts.mono_configure as mono_configure

Import("env")
Import("env_modules")

if env["platform"] == "web":
    if env["library_type"] == "shared_library":
        # Shared library doesn't work right now.
        env["EXPORTED_FUNCTIONS_SHARED"] += ["_set_load_from_executable_fn"]

    env.AddJSLibraries(["web/setjmp_stub.js"])
    env.AddJSPre(["web/callMain_stub.js"])
    env["CUSTOM_GODOT_JS"] = env.File("web/mono_bridge.js")

env_mono = env_modules.Clone()

# Configure Mono

mono_configure.configure(env, env_mono)

# Add sources

env_mono.add_source_files(env.modules_sources, "*.cpp")
env_mono.add_source_files(env.modules_sources, "glue/*.cpp")
env_mono.add_source_files(env.modules_sources, "mono_gd/*.cpp")
env_mono.add_source_files(env.modules_sources, "utils/*.cpp")

if env.editor_build:
    env_mono.add_source_files(env.modules_sources, "editor/*.cpp")
    SConscript("editor/script_templates/SCsub")
elif env.get("library_type", "") == "shared_library":
    # For libgodot shared library builds, we need hostfxr_resolver and semver
    # to discover the system .NET SDK (used via LIBGODOT_HOSTFXR define)
    env_mono.add_source_files(env.modules_sources, "editor/hostfxr_resolver.cpp")
    env_mono.add_source_files(env.modules_sources, "editor/semver.cpp")
